### ISSUE TITLE
Problem in running benchmark scripts

### ISSUE THREAD

**Issue by tdyydt** [Gradual-Typing/benchmarks#18]
Hello, I'm currently trying to run the Grift benchmarks in this repository.

I followed the instructions given in the README (Quick Start Guide):

```
 $ git clone https://github.com/Gradual-Typing/benchmarks.git
 $ cd benchmarks
 $ git checkout pldi19
 $ docker pull dalmahal90/grift-benchmarks:pldi19
```

Then, README says `make release` takes a few days, so I tried others.

When I tried `make test`, it failed with an error:
`awk: ../scripts/lib/geo:9: fatal: division by zero attempted`.
Here is the whole output: [grift-make-test.txt](https://github.com/Gradual-Typing/benchmarks/files/3812562/grift-make-test.txt)

How can I fix this issue? I'd appreciate any help of yours.
I'm doing this on Ubuntu 18.04.03.

**Comment by tdyydt** [comment]
I've been trying VM from [PLDI 2019 artifact](https://dl.acm.org/citation.cfm?id=3325989), and I could confirm benchmark scripts are successfully running there.
I'm going to compare successful outputs on VM with ones on my own environment.
If you have any, could you give me any advices or possible causes?

**Comment by deyaaeldeen** [comment]
Hi, sorry for replying late.

I think this error means that executing the benchmarks failed. It tried to compute the geometric mean of the runtimes collected but there were not any. Also, the output looks off because it indeed does not show any runtimes and it should. I tried the same steps on my redhat machine and it works fine.

One thing you can do is to edit `scripts/Makefile` and prepend `bash -x` to the two lines in the `coarse` recipe, so they be:
```
bash -x ./racket_partial.sh $(ROOT_DIR) $(TIMING_SAMPLES) $(BENCHMARK_DIR) $(INPUT_TYPE)
bash -x ./grift_partial.sh $(ROOT_DIR) $(TIMING_SAMPLES) $(BENCHMARK_DIR) true coarse \
		$(NUM_BINS) $(BIN_SAMPLES) $(INPUT_TYPE) $(CONFIGS)

```
and rerun `make test`. This will print a lot more information that we could use to understand what is going on. Feel free to attach that output here and I will have a look.

**Comment by tdyydt** [comment]
Thank you! I will try that 🙇

**Comment by tdyydt** [comment]
As you advised, I tried prepending `bash -x`. Then, the output becomes like this: [make-test-debug.txt](https://github.com/Gradual-Typing/benchmarks/files/3849934/make-test-debug.txt) 
I will keep investigating more on my own, too.

**Comment by deyaaeldeen** [comment]
Now, to confirm our hypothesis, could you run `make rm-container; make attach` and in the new shell `cat /app/experiments/results/grift/partial/coarse/test/data/sieve17.log`. If that is empty, do `rm -rf /app/experiments/results/grift/partial/coarse/test` and then exit the shell and do `make rm-container; make test`. Make sure that command finishes to the end without any interruptions and capture the output in a file and attach it here and I will have another look.

**Comment by tdyydt** [comment]
I haven't commented yet, but I was investigating a few hours ago.

```
++ cat ../results/grift/partial/coarse/test/tmp/static/sieve17.cache
+ RETURN=0
```

It seems that some cached running time was zero, which caused zero division. When I removed `/home/root/experiments/results/grift/partial/coarse/test/tmp/static/*.cache` files, zero-division error disappeared. (But, I haven't succeeded yet because of another error.)

From now, I'll try the instructions in your last reply 🙇

**Comment by tdyydt** [comment]
And, the output of `make test` has changed. It went through `sieve` and `fft`, but got stuck in `blackscholes`. It fails with an error in `parse-time-program` like:   [make-test-debug-2.txt](https://github.com/Gradual-Typing/benchmarks/files/3852137/make-test-debug-2.txt)
I haven't understood this error well.

**Comment by deyaaeldeen** [comment]
It means that the output of the benchmark is different from the expected on. I think this is due to slight difference in floating point precision. You could disable this check for now by commenting this expression, https://github.com/Gradual-Typing/benchmarks/blob/master/scripts/lib/parse-time.rkt#L51

**Comment by tdyydt** [comment]
Ah, that makes sense to me. Commenting that expression worked, and I could successfully run `make test`! I am really grateful for your help.

In fact, our group has been modifying your Grift compiler, and we're planning to try these benchmark scripts for our modified version of Grift. If I run into another problem, I might want some more help...

**Comment by deyaaeldeen** [comment]
I opened #19 for the `blackscholes` issue so I will close this one. I am glad that worked for you and it is exciting that grift is being used in your work! Please feel free to contact me directly or open another issue if you had further questions/difficulties about using or benchmarking grift.

**Comment by tdyydt** [comment]
Thank you for all your kindness!
